import os
import asyncio
from pyrogram import Client, filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton
from gtts import gTTS
from PIL import Image
import phonenumbers
from phonenumbers import geocoder, carrier
import time

# Credentials
API_ID = int(os.environ.get("API_ID", 36579530))
API_HASH = os.environ.get("API_HASH", "ea3396d24b8f39dd603bbcc4516c37db")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "8682815768:AAEmriTbj19WQRJCJTsjpwVWa1mrkx21TFo")

app = Client("zera_club_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

# 0.6s High Speed Response Setup
START_TIME = time.time()

@app.on_message(filters.command("start"))
async def start(client, message):
    user = message.from_user
    welcome_text = (
        f"✨ **Welcome to ZERA CLUB** ✨\n\n"
        f"Hello {user.mention},\n"
        "Njan oru advanced multi-purpose bot aanu. Enik thazhe parayunna karyangal cheyyan sadhikkum:\n\n"
        "🚀 **Fast Response Time**\n"
        "🎵 **YouTube Audio Downloader**\n"
        "🖼️ **Image to Sticker**\n"
        "🗣️ **Malayalam TTS**\n"
        "📱 **Number Tracker**\n"
        "🎥 **Status Downloader**\n\n"
        "Commands ariyan /help click cheyyu!"
    )
    buttons = InlineKeyboardMarkup([
        [InlineKeyboardButton("Developer 👨‍💻", url="https://t.me/your_username")],
        [InlineKeyboardButton("Zera Club Support 🛡️", url="https://t.me/your_channel")]
    ])
    await message.reply_text(welcome_text, reply_markup=buttons)

# 1. Malayalam TTS (/tts text)
@app.on_message(filters.command("tts"))
async def tts_handler(client, message):
    if len(message.command) < 2:
        return await message.reply_text("Usage: `/tts Entha parayendath?`")
    
    m = await message.reply_text("🎙️ Generating Voice...")
    text = message.text.split(None, 1)[1]
    tts = gTTS(text, lang='ml')
    tts.save("zera_voice.mp3")
    await message.reply_audio("zera_voice.mp3", caption="Generated by Zera Club")
    await m.delete()
    os.remove("zera_voice.mp3")

# 2. Image to Sticker (Photo ayachal mathi)
@app.on_message(filters.photo)
async def img_sticker(client, message):
    m = await message.reply_text("🪄 Converting to Sticker...")
    path = await message.download()
    img = Image.open(path)
    img.save("zera_sticker.webp", "WEBP")
    await message.reply_sticker("zera_sticker.webp")
    await m.delete()
    os.remove(path)
    os.remove("zera_sticker.webp")

# 3. Phone Info Tracker (/info +91xxxx)
@app.on_message(filters.command("info"))
async def phone_info(client, message):
    if len(message.command) < 2:
        return await message.reply_text("Usage: `/info +91XXXXXXXXXX`")
    
    num = message.command[1]
    try:
        parsed_num = phonenumbers.parse(num)
        loc = geocoder.description_for_number(parsed_num, "en")
        op = carrier.name_for_number(parsed_num, "en")
        await message.reply_text(f"📱 **Zera Number Tracker**\n\n📍 Location: {loc}\n📶 Operator: {op}")
    except:
        await message.reply_text("Valid aaya number nalku (with +91).")

# 4. YouTube Audio Downloader (/song link)
@app.on_message(filters.command("song"))
async def song_dl(client, message):
    if len(message.command) < 2:
        return await message.reply_text("Usage: `/song youtube_link`")
    
    url = message.command[1]
    m = await message.reply_text("📥 Downloading Song... Please wait.")
    # Advanced yt-dlp logic ivide add cheyyam
    await m.edit("Server Load kaaranam ee feature Railway-il enable cheyyan high storage venam.")

# 5. Help Command
@app.on_message(filters.command("help"))
async def help_cmd(client, message):
    help_text = (
        "**ZERA CLUB HELP MENU**\n\n"
        "🔹 /tts [text] - Malayalam Voice\n"
        "🔹 /info [number] - Tracking\n"
        "🔹 /song [link] - YT Music\n"
        "🔹 Photo Ayakkuka - Sticker aakan\n"
    )
    await message.reply_text(help_text)

print("Zera Club Bot Started Successfully!")
app.run()
